# Numpy

## basic

In [2]:
import numpy as np

In [4]:
array = [1,2,3,4,5]
array +1

## matrix into numpy
## the very basic, ndarray (numpy)

TypeError: can only concatenate list (not "int") to list

In [6]:
array = np.array([1,2,3,4,5])
print(type(array))

<class 'numpy.ndarray'>


In [8]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [11]:
## the same shape within ndarray
array3 =  array2 + array 
array3

array([ 3,  5,  7,  9, 11])

In [13]:
array4 = array * array2
array4

array([ 2,  6, 12, 20, 30])

In [14]:
## get value in ndarray
## start at 0
array4[0]

2

In [15]:
## shape, dimension row(example) col(features)
array4.shape

(5,)

In [19]:
array2d = np.array([[1,24,5],[3,41,5]])
array2d

array([[ 1, 24,  5],
       [ 3, 41,  5]])

In [20]:
array2d.shape
## two example, each got three features

(2, 3)

## array structure

#### 所有元素必须是统一类型，不然，会向下转化
#### int --> folt --> string

In [43]:
tang_list = [1,2,3,5.0,'33']
tang_array = np.array(tang_list)
tang_array

array(['1', '2', '3', '5.0', '33'], dtype='<U32')

In [44]:
## data type
tang_array.dtype

dtype('<U32')

In [45]:
## number of elements
tang_array.size

5

### 索引+切片

In [46]:
## the third element
tang_array[2]

'3'

In [47]:
## 左开右闭， got the first and second one
tang_array[0:2]

array(['1', '2'], dtype='<U32')

In [48]:
## the last two
tang_array[-2:]

array(['5.0', '33'], dtype='<U32')

### 矩阵格式（多维）

In [51]:
tang_array = np.array([[11,33],[33,441],[33,5454]])
tang_array

array([[  11,   33],
       [  33,  441],
       [  33, 5454]])

In [52]:
tang_array.shape

(3, 2)

In [53]:
tang_array.size

6

In [54]:
tang_array.ndim

2

In [56]:
## get value
tang_array[1,1]

441

In [59]:
tang_array[2,]

array([  33, 5454])

In [60]:
tang_array[:,:]

array([[  11,   33],
       [   0,  441],
       [  33, 5454]])

In [58]:
## change value
tang_array[1,0] = 0
tang_array

array([[  11,   33],
       [   0,  441],
       [  33, 5454]])

In [61]:
##  = hard copy
tang_array2 = tang_array
tang_array2

array([[  11,   33],
       [   0,  441],
       [  33, 5454]])

In [63]:
## the orgin change tooo
tang_array2[1,0] = 10000
tang_array

array([[   11,    33],
       [10000,   441],
       [   33,  5454]])

In [64]:
## XX.copy(), the orign unchange
tang_array3 = tang_array.copy()
tang_array3[1,0] = 1
tang_array

array([[   11,    33],
       [10000,   441],
       [   33,  5454]])

### bool as 索引

In [67]:
## arange(start,end,gap) （依旧左开右闭）
tang_arrayb = np.arange(0,101,10)
tang_arrayb

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [70]:
mask = np.array([0,0,0,0,0,0,0,1,1,1,1],dtype = bool)
mask

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [71]:
## use bool to select data
tang_arrayb[mask]

array([ 70,  80,  90, 100])

In [80]:
## random, [0,1) , shape
## get 10 random number between 0 and 1
random_array = np.random.rand(11)
random_array

array([0.7809552 , 0.42872955, 0.09647013, 0.59157445, 0.61199194,
       0.00176657, 0.28322175, 0.79459287, 0.23024262, 0.27359872,
       0.15833105])

In [81]:
mask =  random_array > 0.5
mask

array([ True, False, False,  True,  True, False, False,  True, False,
       False, False])

In [82]:
tang_arrayb[mask]

array([ 0, 30, 40, 70])

In [83]:
## np.where, skip mask step
np.where(tang_arrayb > 40)

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

In [84]:
tang_arrayb[np.where(tang_arrayb > 40)]

array([ 50,  60,  70,  80,  90, 100])

In [85]:
## astype
tang_arrayb.astype(np.float32)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
      dtype=float32)

## 数值计算

In [4]:
tang_array = np.array([[1,2,3],[4,5,6]])

In [5]:
## sum all the element
np.sum(tang_arary)

21

In [6]:
## sum at col axis
np.sum(tang_arary, axis = 0)

array([5, 7, 9])

In [7]:
## sum at row axis
np.sum(tang_arary, axis = 1)

array([ 6, 15])

In [8]:
## productive at row axis
np.prod(tang_arary, axis = 1)

array([  6, 120])

In [10]:
## get the min at row axis
np.min(tang_arary, axis = 1)
tang_arary.min(axis = 1)

array([1, 4])

In [12]:
## get index at row axis
tang_arary.argmin(axis = 1)

array([0, 0], dtype=int64)

In [13]:
## mean
tang_arary.mean()

3.5

In [15]:
## std
tang_arary.std()

1.707825127659933

In [16]:
## various
tang_arary.var()

2.9166666666666665

In [17]:
## clip (set the min and max limitation in all elements)
tang_arary.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [19]:
## round
tang_array = np.array([1.3,1.456,2.51])
tang_array.round()

array([1., 1., 3.])

In [20]:
## keep digits after .
tang_array.round(decimals = 2)

array([1.3 , 1.46, 2.51])

## 排序

In [37]:
tang_array = np.array([[1.1,10.456,2.51],[3.4,9.3,9.33]])
tang_array.sort()
tang_array

array([[ 1.1  ,  2.51 , 10.456],
       [ 3.4  ,  9.3  ,  9.33 ]])

In [40]:
tang_array.sort(axis = 1)
tang_array

array([[ 1.1  ,  2.51 ,  9.33 ],
       [ 3.4  ,  9.3  , 10.456]])

In [43]:
## np.linspace(start, end, num)
## very similar to np.range,but the end number inculude
tang_array = np.linspace(0,10,10)
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [47]:
## Find indices where elements should be inserted to maintain order
## find the indices in the orgin array, the return indice number is the the least large number indice
value = np.array([6.8,4.445,9.4])
np.searchsorted(tang_array,value)

array([7, 5, 9], dtype=int64)

In [51]:
tang_array = np.array([[1,3,6],[2,4,7],[1,2,3]])
tang_array

array([[1, 3, 6],
       [2, 4, 7],
       [1, 2, 3]])

In [61]:
## lexsort
np.lexsort([tang_array[:,1], tang_array[:,2]])

array([2, 0, 1], dtype=int64)

In [62]:
?np.lexsort

## 数据形状


In [90]:
tang_array = np.arange(24)
tang_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
tang_array.shape = [2,3,4]
tang_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [87]:
tang_array.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [91]:
## add a new axis
tang_array.reshape(1,24)
tang_array[np.newaxis,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [93]:
## remove empity axis
tang_array.squeeze()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
## 装置
tang_array.shape = [2,3,4]
tang_array.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [135]:
## concatenate
a = np.arange(0,30,1)
a.shape = [2,3,5]
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [138]:
b = np.arange(10,40,1)
b.shape = [2,3,5]
b

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [143]:
## the axis = 0 (defalut), means the caculate at the first [] level
np.concatenate((a,b), axis = 0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [145]:
## the axis = 2, means the caculate at the second [] level
np.concatenate((a,b), axis = 2)

array([[[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 20, 21, 22, 23, 24]],

       [[15, 16, 17, 18, 19, 25, 26, 27, 28, 29],
        [20, 21, 22, 23, 24, 30, 31, 32, 33, 34],
        [25, 26, 27, 28, 29, 35, 36, 37, 38, 39]]])

In [148]:
## the a & b shape is 2,3,5

## the vertical equal to axis = 0
v = np.vstack((a,b))
v.shape

(4, 3, 5)

In [149]:
## the herizon equal to axis = 1
h = np.hstack((a,b))
h.shape

(2, 6, 5)

In [150]:
## transform to only 1 dimension
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39])

## 数组生成

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.linspace(0,10,5, dtype = np.float32)

array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)

### log

In [8]:
## log10
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### zeros ones

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
w1 = np.ones((4,3))

In [13]:
np.empty(3)

array([0., 0., 0.])

In [27]:
w1[0,2] = 100
w1

array([[  1.,   1., 100.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [29]:
## copp the shape, and give inital value 0/1
np.zeros_like(w1)
np.ones_like(w1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 随机模块

In [34]:
np.random.rand(3,2)

array([[0.58801768, 0.38972385],
       [0.23676117, 0.66496699],
       [0.57162517, 0.14574781]])

In [40]:
## range from 0 - 12 ,左闭右开
np.random.randint(12,size = (3,2))

array([[ 5,  7],
       [ 1, 11],
       [ 2,  6]])

In [42]:
np.random.randint(12,25,5)

array([19, 16, 19, 18, 13])

In [45]:
## Return random floats in the half-open interval [0.0, 1.0)
np.random.random_sample()

In [47]:
## 随机高斯分布
mu = 10 
sigma = 4
np.random.normal(mu,sigma, 10)

array([20.26504505,  9.87195602, 16.32727711, 12.32496727,  5.95872818,
       15.31774402, 10.00293288, 12.71734623,  8.78296441, 11.60983495])

In [70]:
## 保留特定小数点个数
np.set_printoptions(precision= 4)

In [49]:
mu = 10 
sigma = 4
np.random.normal(mu,sigma, 10)

array([ 7.6158,  2.009 , 15.0859,  8.6896, 18.4999,  5.8556, 18.0106,
        9.675 , 11.7933,  7.1868])

In [71]:
### 洗牌 shuffle
tang = np.arange(10)
np.random.shuffle(tang)
tang

array([4, 5, 6, 9, 8, 0, 2, 7, 3, 1])

In [72]:
## 随机种子
np.random.seed(101)
mu = 10 
sigma = 4
np.random.normal(mu,sigma, 10)

array([20.8274, 12.5125, 13.6319, 12.0153, 12.6045,  8.7227,  6.6077,
       12.4239,  1.9273, 12.9605])

## 运算

In [7]:
## 乘法
x = np.array([[2,2],[2,2]])
y = np.array([[5,5],[5,5]])
np.multiply(x,y)

array([[10, 10],
       [10, 10]])

In [19]:
## 内积（一维时，相同位置相乘再相加）
x = np.array([1,2])
y = np.array([3,4])
np.dot(x,y)

11

In [20]:
x.shape = (1,2)
y.shape = (2,1)

In [21]:
x

array([[1, 2]])

In [22]:
y

array([[3],
       [4]])

In [23]:
## 矩阵计算，前后有别
np.dot(x,y)

array([[11]])

In [24]:
np.dot(y,x)

array([[3, 6],
       [4, 8]])

### 逻辑运算

In [26]:
x = np.array([1,1,1,3])
y = np.array([1,1,1,1])

In [27]:
x == y

array([ True,  True,  True, False])

In [29]:
np.logical_and([True, False], [False, False])

array([False, False])

In [30]:
np.logical_or([True, False], [False, False])

array([ True, False])

## 文件读写

In [75]:
tang.shape=(2,5)
tang

array([[4, 5, 6, 9, 8],
       [0, 2, 7, 3, 1]])

In [76]:
np.savetxt('tang.txt',tang)

In [84]:
## 保留整数
np.savetxt('tang1.txt',tang, fmt = '%d')

In [90]:
## 保留2位小数
np.savetxt('tang2.txt',tang, fmt = '%.2f')

In [91]:
## 改变间隔符
np.savetxt('tang3.txt',tang, delimiter= "--")

In [78]:
data = np.loadtxt('tang.txt')
data

array([[4., 5., 6., 9., 8.],
       [0., 2., 7., 3., 1.]])

In [79]:
data = np.loadtxt('tang.txt', skiprows= 1)
data

array([0., 2., 7., 3., 1.])

In [81]:
data = np.loadtxt('tang.txt', delimiter= " ")
data

array([[4., 5., 6., 9., 8.],
       [0., 2., 7., 3., 1.]])

### array 读写
#### 保存中间数据，节省时间

In [92]:
tang

array([[4, 5, 6, 9, 8],
       [0, 2, 7, 3, 1]])

In [94]:
np.save('tang_array.npy', tang)

In [96]:
tang = np.load('tang_array.npy')
tang

array([[4, 5, 6, 9, 8],
       [0, 2, 7, 3, 1]])

In [103]:
import os
os.path.abspath('.')

'D:\\Python\\唐宇迪-机器学习课程\\Python库代码（4个）'